# Generated by Django 4.1.1 on 2022-12-06 19:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student_app', '0004_extendeduser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ExtendedUser',
        ),
    ]
